global:
  scrape_interval: 5s  # interval between two successive scraping

scrape_configs:

  - job_name: 'infra_vm-docker'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000', ]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090', ]

rule_files:
  - "/etc/prometheus/alert.rules.yml"
